version: "3.8"
services:
    nodeserver:
        build:
            context: ./server
        ports:
            - "3000:3000"
    nginx:
        restart: always
        build:
            context: ./nginx
        ports:
            - "80:80"
        depends_on:
            - nodeserver